// Mocks generated by Mockito 5.4.3 from annotations
// in aplicativo_de_tarefas/test/provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i3;

import 'package:aplicativo_de_tarefas/main.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TarefaProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockTarefaProvider extends _i1.Mock implements _i2.TarefaProvider {
  MockTarefaProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Tarefa> get tarefas => (super.noSuchMethod(
        Invocation.getter(#tarefas),
        returnValue: <_i2.Tarefa>[],
      ) as List<_i2.Tarefa>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void adicionarTarefa(_i2.Tarefa? tarefa) => super.noSuchMethod(
        Invocation.method(
          #adicionarTarefa,
          [tarefa],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removerTarefa(_i2.Tarefa? tarefa) => super.noSuchMethod(
        Invocation.method(
          #removerTarefa,
          [tarefa],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
